import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const cinzel = Cinzel({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: "#E1F0DA" }}>
      <body className={cinzel.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
